name: Lottery Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Test with pytest
        run: pytest

  docker-smoke-test:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t lottery-app .

      - name: Run the container
        run: docker run -d -p 5000:8000 -v ci-test-data:/data lottery-app

      - name: Wait for the application to start
        run: sleep 10

      - name: Perform a smoke test
        run: curl --fail http://localhost:5000/ping
